version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: pass
    networks: 
      - mynetwork

  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - 8080:80
    networks: 
      - mynetwork

volumes: 
  db_data:      

networks: 
  mynetwork: